# Generated by Django 6.0.1 on 2026-02-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('description', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cost', models.IntegerField(help_text='旅費（円）')),
                ('duration', models.CharField(help_text='所要時間', max_length=50)),
                ('transportation', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='感想')),
                ('category', models.CharField(choices=[('night_view', '夜景'), ('friends', '友達と'), ('couple', 'カップル')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
