# Generated by Django 6.0.1 on 2026-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'おすすめの旅先', 'verbose_name_plural': 'おすすめの旅先一覧'},
        ),
        migrations.AlterModelOptions(
            name='travelpost',
            options={'verbose_name': '旅行投稿', 'verbose_name_plural': '旅行投稿一覧'},
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='title',
        ),
        migrations.AddField(
            model_name='travelpost',
            name='end_point',
            field=models.CharField(default='', max_length=100, verbose_name='到着地点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpost',
            name='start_point',
            field=models.CharField(default='', max_length=100, verbose_name='出発地点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpost',
            name='via_points',
            field=models.CharField(blank=True, help_text='経由した場所を「、」や「➔」で区切って入力してください', max_length=200, verbose_name='経由地点'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='destinations/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, verbose_name='旅先名'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='reason',
            field=models.TextField(verbose_name='おすすめの理由'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='category',
            field=models.CharField(choices=[('night_view', '夜景'), ('friends', '友達と'), ('couple', 'カップル')], max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='content',
            field=models.TextField(verbose_name='思い出の感想'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='cost',
            field=models.IntegerField(help_text='数値のみ入力してください', verbose_name='旅費（円）'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='所要時間'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='transportation',
            field=models.CharField(max_length=100, verbose_name='交通手段'),
        ),
    ]
