# Generated by Django 6.0.1 on 2026-02-05 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_destination_options_alter_travelpost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='via_points',
            field=models.TextField(blank=True, default='', help_text='JSON形式で経由地点を保存（自動生成）', verbose_name='経由地点'),
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('days', models.IntegerField(verbose_name='日数')),
                ('plan_content', models.TextField(verbose_name='プラン内容')),
                ('favorite_food', models.CharField(blank=True, max_length=20, verbose_name='食べ物')),
                ('favorite_activity', models.CharField(blank=True, max_length=20, verbose_name='アクティビティ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅行プラン',
                'verbose_name_plural': '旅行プラン一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_food', models.CharField(choices=[('japanese', '和食'), ('italian', 'イタリアン'), ('chinese', '中華'), ('french', 'フランス料理'), ('korean', '韓国料理'), ('local', 'ローカルグルメ'), ('no_preference', '特になし')], default='no_preference', max_length=20, verbose_name='好きな食べ物')),
                ('favorite_activity', models.CharField(choices=[('sightseeing', '観光'), ('nature', '自然'), ('culture', '文化'), ('sports', 'スポーツ'), ('shopping', 'ショッピング'), ('nightlife', 'ナイトライフ'), ('relax', 'リラックス'), ('no_preference', '特になし')], default='no_preference', max_length=20, verbose_name='好きなアクティビティ')),
                ('budget_per_day', models.IntegerField(default=10000, verbose_name='1日の予算（円）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー旅行好み',
                'verbose_name_plural': 'ユーザー旅行好み',
            },
        ),
    ]
