# Generated by Django 6.0.1 on 2026-02-05 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_travelpost_via_points_travelplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoints', models.TextField(default='[]', help_text='[{"lat": 35.6762, "lng": 139.6503, "name": "地点名", "date": "2026-02-06"}, ...]', verbose_name='ウェイポイント')),
                ('total_distance', models.FloatField(default=0, verbose_name='総距離（km）')),
                ('total_duration', models.IntegerField(default=0, verbose_name='総所要時間（分）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='travel.travelplan')),
            ],
            options={
                'verbose_name': '旅行ルート',
                'verbose_name_plural': '旅行ルート一覧',
            },
        ),
    ]
