# Generated by Django 6.0.1 on 2026-02-06 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travelpost_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='video',
            field=models.FileField(blank=True, help_text='MP4、WebMなどの動画ファイル', null=True, upload_to='posts/', verbose_name='動画'),
        ),
    ]
