# Generated by Django 6.0.1 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_travelpost_image_travelpost_user_travelpost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='photo_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='写真の場所'),
        ),
    ]
