# Generated by Django 6.0.1 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_travelpost_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='start_point',
            field=models.CharField(blank=True, max_length=100, verbose_name='出発地点'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='end_point',
            field=models.CharField(blank=True, max_length=100, verbose_name='到着地点'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='cost',
            field=models.IntegerField(blank=True, help_text='数値のみ入力してください', null=True, verbose_name='旅費（円）'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='所要時間'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='content',
            field=models.TextField(blank=True, verbose_name='思い出の感想'),
        ),
    ]

