# Generated by Django 6.0.1 on 2026-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_travelpost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='transportation',
            field=models.CharField(choices=[('walk', '徒歩'), ('bike', '自転車'), ('car', 'くるま'), ('bus', 'バス'), ('train', '電車'), ('shinkansen', '新幹線'), ('plane', '飛行機')], default='walk', max_length=20, verbose_name='交通手段'),
        ),
    ]
